name: scoop
description: Quick news bites and information


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  figma_squircle: ^0.5.3
  blur: ^3.1.0
  flutter_feather_icons: ^2.0.0+1
  modal_bottom_sheet: ^2.1.2
  sheet: ^0.0.4+1
  http: ^0.13.5
  ionicons: ^0.2.1
  liquid_pull_to_refresh: ^3.0.1
  localstorage: ^4.0.0+1
  pull_down_button: ^0.4.0
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - lib/assets/horizontal.png
    - lib/assets/vertical.png